#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================
get__allow_registration() {
        allow_registration=$(ynh_app_setting_get --app $app --key allow_registration)
        echo "${allow_registration}"
}

get__registration_token() {
	registration_token=$(ynh_app_setting_get --app $app --key registration_token)
	echo "${registration_token}"
}
#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__allow_registration() {
        ynh_app_setting_set --app=$app --key=allow_registration --value="${allow_registration}"
        if [ "$allow_registration" = "true" ] ; then
            sed -i "s|registration_token=|#registration_token=|g" "$install_dir/conduit.toml"
        elif [ "$allow_registration" = "false" ] ; then
            sed -i "s|#registration_token=|registration_token=|g" "$install_dir/conduit.toml"
        fi
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
