#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
registration=$(ynh_app_setting_get --app=$app --key=registration)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

if [ "$registration" = "true" ] ; then
    sed -i -r "s|registration_token="|#registration_token="|g" "$install_dir/conduit.toml"
elif [ "$registration" = "false" ] ; then
    sed -i -r "s|#registration_token="|registration_token="|g" "$install_dir/conduit.toml"
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
