#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

#=================================================
# SPECIFIC VALIDATORS FOR TOML SHORT KEYS
#=================================================

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__allow_federation() {
        if [ "$allow_federation" = "true" ] ; then
        sed -i "s|allow_federation = false|allow_federation = true|g" "$install_dir/conduit.toml"
        yunohost user permission add conduit visitors
        elif [ "$allow_federation" = "false" ] ; then
        sed -i "s|allow_federation = true|allow_federation = false|g" "$install_dir/conduit.toml"
        yunohost user permission remove conduit visitors
        fi
        ynh_app_setting_set --app=$app --key=allow_federation --value="${allow_federation}"
}

#=================================================
# GENERIC FINALIZATION
#=================================================
ynh_app_config_run $1
